### ISSUE TITLE
Testing of Automatic Port Detector

### ISSUE THREAD

**Issue by dward2** [sosophiemw/bass-readyview-app#7]
@sosophiemw We may need to do some additional testing of the automatic port detector because it caused the software to freeze on my computer.

My system has an active use of COM1.  

If we look at the current code for detecting ports:
https://github.com/sosophiemw/bass-readyview-app/blob/3e0763b8b572656f81874d1315f2c13b656b6aab/standalone.py#L78-L92

The idea was that if a port didn't exist, line 80 would cause an error which the `except` block would catch and then move on to the next COM port.  If the port does exist, the idea was that the commands in lines 82 and 83 would send a command to the serial port and then lines 84 to 89 would check the response to see if the response was it should be if the COM port is attached to the inclinometer.  If so, we could say that this is the correct port.  If not, we would move on and keep checking.  

On my computer, COM 1 is detected, and so lines 82 and on are executed.  The problem comes in at line 85.  My COM port doesn't provide any response, and so the program sits at this line and waits.  It waits forever since no response comes.  

The fix for this, at least it worked for me, is to set a timeout duration in the original connection to the Serial port on line 80.  After `write_timeout=5`, I added `, timeout=1` inside the `()` so I ended up with this:

```python
ser = serial.Serial(port, baudrate=115200, bytesize=serial.EIGHTBITS,
                    parity=serial.PARITY_NONE, stopbits=serial.STOPBITS_ONE, write_timeout=5, timeout=1)
```
Now, when the `ser.readline()` command doesn't respond in one second, the program will continue.  And, since `s` will not have the correct info, this port will not be added to the `result` list.

Would you make this change in your code and make sure it doesn't break anything for you?

And, this highlights that, at some point, we will want to take our software and run it on many different computers with many different configurations to make sure it is "field ready" for any kind of set-up.

**Comment by sosophiemw** [comment]
Your fix seems to work for me, so I will make that edit.
