### ISSUE TITLE
Color Temperature Adjustment is Hardcoded for 640x480 image size

### ISSUE THREAD

**Issue by dward2** [sosophiemw/bass-readyview-app#9]
The code for adjusting the color temperature of the image is hard-coded to 640 image width based on these lines:
https://github.com/sosophiemw/bass-readyview-app/blob/3e0763b8b572656f81874d1315f2c13b656b6aab/standalone.py#L333-L335

If other image sizes are acquired from the camera, this code may cause a problem.  Should be adjusted to be based on actual image size.

**Comment by sosophiemw** [comment]
Fixed!
